# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 379)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setObjectName("btnSalvar")
        self.gridLayout.addWidget(self.btnSalvar, 3, 5, 1, 1)
        self.btnRedimencionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedimencionar.setObjectName("btnRedimencionar")
        self.gridLayout.addWidget(self.btnRedimencionar, 2, 5, 1, 1)
        self.Altura = QtWidgets.QLabel(self.centralwidget)
        self.Altura.setObjectName("Altura")
        self.gridLayout.addWidget(self.Altura, 2, 2, 1, 1)
        self.inputLagura = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLagura.setObjectName("inputLagura")
        self.gridLayout.addWidget(self.inputLagura, 2, 1, 1, 1)
        self.btnEscolherArquivo = QtWidgets.QPushButton(self.centralwidget)
        self.btnEscolherArquivo.setObjectName("btnEscolherArquivo")
        self.gridLayout.addWidget(self.btnEscolherArquivo, 1, 5, 1, 1)
        self.inputAltura = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAltura.setObjectName("inputAltura")
        self.gridLayout.addWidget(self.inputAltura, 2, 3, 1, 1)
        self.lagura = QtWidgets.QLabel(self.centralwidget)
        self.lagura.setObjectName("lagura")
        self.gridLayout.addWidget(self.lagura, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 514, 272))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.areaImagem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.areaImagem.setText("")
        self.areaImagem.setObjectName("areaImagem")
        self.gridLayout_2.addWidget(self.areaImagem, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 6)
        self.imputAbrirArquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.imputAbrirArquivo.setObjectName("imputAbrirArquivo")
        self.gridLayout.addWidget(self.imputAbrirArquivo, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "redimensionar imagem"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar"))
        self.btnRedimencionar.setText(_translate("MainWindow", "Redimencionar"))
        self.Altura.setText(_translate("MainWindow", "Altura"))
        self.btnEscolherArquivo.setText(_translate("MainWindow", "Abrir arquivo"))
        self.lagura.setText(_translate("MainWindow", "Lagura"))
